kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: mysql-pv
  resources:
    requests:
      storage: 5Gi